# docker-compose.training.yml



services:
  training:
    build:
      context: ./training # Контекст сборки: папка training/
      dockerfile: Dockerfile.training # Использовать этот Dockerfile
    container_name: dsproject_training
    volumes:
      # Монтирование папки custom_dataset
      - ./training/custom_dataset:/app/custom_dataset
      # Монтирование общей папки shared_data
      - ./shared_data:/app/shared_data
    # Если вы используете GPU для обучения (требует образа CUDA и установленного NVIDIA Container Toolkit)
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]
    # environment:
    #   - NVIDIA_VISIBLE_DEVICES=all
    #   - NVIDIA_DRIVER_CAPABILITIES=all
    # command: python train_yolo.py --data custom_dataset/data.yaml --epochs 50 --imgsz 640
