

    services:
      app:
        build:
          context: . # <--- ИЗМЕНЕНО: Контекст теперь корень проекта DSProject5
          dockerfile: ./app/Dockerfile # <--- ИЗМЕНО: Указываем полный путь к Dockerfile внутри контекста
        ports:
          - "5000:5000"
        volumes:
          - ./shared_data:/shared_data # Монтируем shared_data
          - ./videos:/app/videos       # Монтируем папку с видео
          - ./app/output:/app/output   # Монтируем папку output для снимков
        environment:
          - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
          - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
        deploy:
          resources:
            reservations:
              devices:
                - driver: nvidia
                  count: all
                  capabilities: [gpu]
        depends_on:
          - telegram

      telegram:
        build:
          context: ./telegram
          dockerfile: Dockerfile
        ports:
          - "5001:5001"
        environment:
          - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
          - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
          - TELEGRAM_FLASK_PORT=5001
        volumes:
          - ./shared_data:/shared_data
          - ./app/output:/app/output
    