# docker-compose.app.yml


services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "5000:5000"
    volumes:
      - ./shared_data:/shared_data # Монтируем shared_data
      - ./videos:/app/videos       # Монтируем папку с видео
      - ./app/output:/app/output   # Монтируем папку output для снимков
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
    # === Добавляем секцию deploy для GPU ===
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all # Можно указать конкретное количество GPU, если их несколько, но 'all' проще
              capabilities: [gpu]
    # =======================================

  telegram:
    build:
      context: .
      dockerfile: Dockerfile.telegram
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
    volumes:
      - ./shared_data:/shared_data
      - ./app/output:/app/output
    # Telegram-бот не нуждается в доступе к GPU
